/**
 * 营口机车影像 · 作品数据（sync-works.py 自动生成）
 * -------------------------------------------------------
 * 精选三栏项目文件夹：
 *   assets/portfolio/photo/城市追光/   动态跟拍视频
 *   assets/portfolio/photo/夜色锋芒/   夜间拍摄素材
 *   assets/portfolio/photo/港湾日光/   白天拍摄素材
 *
 * AIGC：
 *   assets/portfolio/aigc/video/项目名/
 *   assets/portfolio/aigc/design/项目名/
 *
 * 双击「更新作品.command」同步。改标题见 titles.json。
 */

window.FEATURED_PROJECTS = [
  {
    id: "slot-城市追光",
    number: "01",
    layout: "wide",
    type: "video",
    label: "城市追光",
    title: "沿海公路 / Red Line",
    subtitle: "动态跟拍电影感短片 · 点击查看项目",
    src: "assets/portfolio/photo/城市追光/沿海公路/沿海公路.mp4",
    cover: "assets/portfolio/photo/城市追光/沿海公路/cover.jpg",
    open: "photo-slot:城市追光",
    folder: "城市追光",
  },
  {
    id: "slot-夜色锋芒",
    number: "02",
    layout: "normal",
    type: "image",
    label: "约拍作品集",
    title: "夜色锋芒 / Night Edge",
    subtitle: "夜间拍摄素材 · 点击查看项目",
    src: "assets/portfolio/photo/夜色锋芒/cover.jpg",
    cover: "assets/portfolio/photo/夜色锋芒/cover.jpg",
    open: "photo-slot:夜色锋芒",
    folder: "夜色锋芒",
  },
  {
    id: "slot-港湾日光",
    number: "03",
    layout: "normal",
    type: "image",
    label: "日间约拍",
    title: "港湾日光 / Harbor Light",
    subtitle: "白天拍摄素材 · 点击查看项目",
    src: "assets/portfolio/photo/港湾日光/cover.jpg",
    cover: "assets/portfolio/photo/港湾日光/cover.jpg",
    open: "photo-slot:港湾日光",
    folder: "港湾日光",
  },
];

window.AIGC_HOME = {
  kicker: "GENERATIVE / MOTION / DESIGN",
  title: "AIGC",
  titleEm: "作品集",
  intro: "用生成式影像拓展机车摄影之外的视觉表达。这里持续收录 AI 视频与 AI 设计项目。",
  cover: "assets/portfolio/aigc/aigc-section-cover.jpg",
  categories: [
    {
      num: "01",
      en: "AI MOTION",
      title: "AI 视频作品",
      desc: "按项目查看动态影像与概念短片。",
      filter: "ai-video",
    },
    {
      num: "02",
      en: "AI DESIGN",
      title: "AI 设计作品",
      desc: "按项目查看设计内容与系列画面。",
      filter: "ai-design",
    },
  ],
};

window.PHOTO_PROJECTS = [
  {
    id: "photo-城市追光-沿海公路",
    folder: "沿海公路",
    path: "城市追光/沿海公路",
    slot: "城市追光",
    cat: "film",
    title: "沿海公路",
    cover: "assets/portfolio/photo/城市追光/沿海公路/cover.jpg",
    count: 1,
    items: [
      {
        id: "film-沿海公路-沿海公路",
        cat: "film",
        type: "video",
        title: "沿海公路",
        meta: "摄影约拍 · 动态跟拍 · 沿海公路",
        cover: "assets/portfolio/photo/城市追光/沿海公路/cover.jpg",
        src: "assets/portfolio/photo/城市追光/沿海公路/沿海公路.mp4",
        project: "沿海公路",
      },
    ],
  },
  {
    id: "photo-夜色锋芒-夜色约拍",
    folder: "夜色约拍",
    path: "夜色锋芒/夜色约拍",
    slot: "夜色锋芒",
    cat: "moto-night",
    title: "夜色约拍",
    cover: "assets/portfolio/photo/夜色锋芒/夜色约拍/cover.jpg",
    count: 7,
    items: [
      {
        id: "moto-night-夜色约拍-夜色约拍-01",
        cat: "moto-night",
        type: "image",
        title: "夜色约拍 · 01",
        meta: "摄影约拍 · 夜间素材 · 夜色约拍",
        src: "assets/portfolio/photo/夜色锋芒/夜色约拍/web/夜色约拍-01.jpg",
        project: "夜色约拍",
      },
      {
        id: "moto-night-夜色约拍-夜色约拍-02",
        cat: "moto-night",
        type: "image",
        title: "夜色约拍 · 02",
        meta: "摄影约拍 · 夜间素材 · 夜色约拍",
        src: "assets/portfolio/photo/夜色锋芒/夜色约拍/web/夜色约拍-02.jpg",
        project: "夜色约拍",
      },
      {
        id: "moto-night-夜色约拍-夜色约拍-03",
        cat: "moto-night",
        type: "image",
        title: "夜色约拍 · 03",
        meta: "摄影约拍 · 夜间素材 · 夜色约拍",
        src: "assets/portfolio/photo/夜色锋芒/夜色约拍/web/夜色约拍-03.jpg",
        project: "夜色约拍",
      },
      {
        id: "moto-night-夜色约拍-夜色约拍-04",
        cat: "moto-night",
        type: "image",
        title: "夜色约拍 · 04",
        meta: "摄影约拍 · 夜间素材 · 夜色约拍",
        src: "assets/portfolio/photo/夜色锋芒/夜色约拍/web/夜色约拍-04.jpg",
        project: "夜色约拍",
      },
      {
        id: "moto-night-夜色约拍-夜色约拍-05",
        cat: "moto-night",
        type: "image",
        title: "夜色约拍 · 05",
        meta: "摄影约拍 · 夜间素材 · 夜色约拍",
        src: "assets/portfolio/photo/夜色锋芒/夜色约拍/web/夜色约拍-05.jpg",
        project: "夜色约拍",
      },
      {
        id: "moto-night-夜色约拍-夜色约拍-06",
        cat: "moto-night",
        type: "image",
        title: "夜色约拍 · 06",
        meta: "摄影约拍 · 夜间素材 · 夜色约拍",
        src: "assets/portfolio/photo/夜色锋芒/夜色约拍/web/夜色约拍-06.jpg",
        project: "夜色约拍",
      },
      {
        id: "moto-night-夜色约拍-夜色约拍-07",
        cat: "moto-night",
        type: "image",
        title: "夜色约拍 · 07",
        meta: "摄影约拍 · 夜间素材 · 夜色约拍",
        src: "assets/portfolio/photo/夜色锋芒/夜色约拍/web/夜色约拍-07.jpg",
        project: "夜色约拍",
      },
    ],
  },
  {
    id: "photo-港湾日光-胖胖",
    folder: "胖胖",
    path: "港湾日光/胖胖",
    slot: "港湾日光",
    cat: "moto-day",
    title: "胖胖",
    cover: "assets/portfolio/photo/港湾日光/胖胖/cover.jpg",
    count: 10,
    items: [
      {
        id: "moto-day-胖胖-胖胖-01",
        cat: "moto-day",
        type: "image",
        title: "胖胖 · 01",
        meta: "摄影约拍 · 日间素材 · 胖胖",
        src: "assets/portfolio/photo/港湾日光/胖胖/web/胖胖-01.jpg",
        project: "胖胖",
      },
      {
        id: "moto-day-胖胖-胖胖-02",
        cat: "moto-day",
        type: "image",
        title: "胖胖 · 02",
        meta: "摄影约拍 · 日间素材 · 胖胖",
        src: "assets/portfolio/photo/港湾日光/胖胖/web/胖胖-02.jpg",
        project: "胖胖",
      },
      {
        id: "moto-day-胖胖-胖胖-03",
        cat: "moto-day",
        type: "image",
        title: "胖胖 · 03",
        meta: "摄影约拍 · 日间素材 · 胖胖",
        src: "assets/portfolio/photo/港湾日光/胖胖/web/胖胖-03.jpg",
        project: "胖胖",
      },
      {
        id: "moto-day-胖胖-胖胖-04",
        cat: "moto-day",
        type: "image",
        title: "胖胖 · 04",
        meta: "摄影约拍 · 日间素材 · 胖胖",
        src: "assets/portfolio/photo/港湾日光/胖胖/web/胖胖-04.jpg",
        project: "胖胖",
      },
      {
        id: "moto-day-胖胖-胖胖-05",
        cat: "moto-day",
        type: "image",
        title: "胖胖 · 05",
        meta: "摄影约拍 · 日间素材 · 胖胖",
        src: "assets/portfolio/photo/港湾日光/胖胖/web/胖胖-05.jpg",
        project: "胖胖",
      },
      {
        id: "moto-day-胖胖-胖胖-06",
        cat: "moto-day",
        type: "image",
        title: "胖胖 · 06",
        meta: "摄影约拍 · 日间素材 · 胖胖",
        src: "assets/portfolio/photo/港湾日光/胖胖/web/胖胖-06.jpg",
        project: "胖胖",
      },
      {
        id: "moto-day-胖胖-胖胖-07",
        cat: "moto-day",
        type: "image",
        title: "胖胖 · 07",
        meta: "摄影约拍 · 日间素材 · 胖胖",
        src: "assets/portfolio/photo/港湾日光/胖胖/web/胖胖-07.jpg",
        project: "胖胖",
      },
      {
        id: "moto-day-胖胖-胖胖-08",
        cat: "moto-day",
        type: "image",
        title: "胖胖 · 08",
        meta: "摄影约拍 · 日间素材 · 胖胖",
        src: "assets/portfolio/photo/港湾日光/胖胖/web/胖胖-08.jpg",
        project: "胖胖",
      },
      {
        id: "moto-day-胖胖-胖胖-09",
        cat: "moto-day",
        type: "image",
        title: "胖胖 · 09",
        meta: "摄影约拍 · 日间素材 · 胖胖",
        src: "assets/portfolio/photo/港湾日光/胖胖/web/胖胖-09.jpg",
        project: "胖胖",
      },
      {
        id: "moto-day-胖胖-胖胖-10",
        cat: "moto-day",
        type: "image",
        title: "胖胖 · 10",
        meta: "摄影约拍 · 日间素材 · 胖胖",
        src: "assets/portfolio/photo/港湾日光/胖胖/web/胖胖-10.jpg",
        project: "胖胖",
      },
    ],
  },
  {
    id: "photo-港湾日光-芒果",
    folder: "芒果",
    path: "港湾日光/芒果",
    slot: "港湾日光",
    cat: "moto-day",
    title: "芒果",
    cover: "assets/portfolio/photo/港湾日光/芒果/web/芒果-01.jpg",
    count: 25,
    items: [
      {
        id: "moto-day-芒果-芒果-01",
        cat: "moto-day",
        type: "image",
        title: "芒果 · 01",
        meta: "摄影约拍 · 日间素材 · 芒果",
        src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-01.jpg",
        project: "芒果",
      },
      {
        id: "moto-day-芒果-芒果-02",
        cat: "moto-day",
        type: "image",
        title: "芒果 · 02",
        meta: "摄影约拍 · 日间素材 · 芒果",
        src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-02.jpg",
        project: "芒果",
      },
      {
        id: "moto-day-芒果-芒果-03",
        cat: "moto-day",
        type: "image",
        title: "芒果 · 03",
        meta: "摄影约拍 · 日间素材 · 芒果",
        src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-03.jpg",
        project: "芒果",
      },
      {
        id: "moto-day-芒果-芒果-04",
        cat: "moto-day",
        type: "image",
        title: "芒果 · 04",
        meta: "摄影约拍 · 日间素材 · 芒果",
        src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-04.jpg",
        project: "芒果",
      },
      {
        id: "moto-day-芒果-芒果-05",
        cat: "moto-day",
        type: "image",
        title: "芒果 · 05",
        meta: "摄影约拍 · 日间素材 · 芒果",
        src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-05.jpg",
        project: "芒果",
      },
      {
        id: "moto-day-芒果-芒果-06",
        cat: "moto-day",
        type: "image",
        title: "芒果 · 06",
        meta: "摄影约拍 · 日间素材 · 芒果",
        src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-06.jpg",
        project: "芒果",
      },
      {
        id: "moto-day-芒果-芒果-07",
        cat: "moto-day",
        type: "image",
        title: "芒果 · 07",
        meta: "摄影约拍 · 日间素材 · 芒果",
        src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-07.jpg",
        project: "芒果",
      },
      {
        id: "moto-day-芒果-芒果-08",
        cat: "moto-day",
        type: "image",
        title: "芒果 · 08",
        meta: "摄影约拍 · 日间素材 · 芒果",
        src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-08.jpg",
        project: "芒果",
      },
      {
        id: "moto-day-芒果-芒果-09",
        cat: "moto-day",
        type: "image",
        title: "芒果 · 09",
        meta: "摄影约拍 · 日间素材 · 芒果",
        src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-09.jpg",
        project: "芒果",
      },
      {
        id: "moto-day-芒果-芒果-10",
        cat: "moto-day",
        type: "image",
        title: "芒果 · 10",
        meta: "摄影约拍 · 日间素材 · 芒果",
        src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-10.jpg",
        project: "芒果",
      },
      {
        id: "moto-day-芒果-芒果-11",
        cat: "moto-day",
        type: "image",
        title: "芒果 · 11",
        meta: "摄影约拍 · 日间素材 · 芒果",
        src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-11.jpg",
        project: "芒果",
      },
      {
        id: "moto-day-芒果-芒果-12",
        cat: "moto-day",
        type: "image",
        title: "芒果 · 12",
        meta: "摄影约拍 · 日间素材 · 芒果",
        src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-12.jpg",
        project: "芒果",
      },
      {
        id: "moto-day-芒果-芒果-13",
        cat: "moto-day",
        type: "image",
        title: "芒果 · 13",
        meta: "摄影约拍 · 日间素材 · 芒果",
        src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-13.jpg",
        project: "芒果",
      },
      {
        id: "moto-day-芒果-芒果-14",
        cat: "moto-day",
        type: "image",
        title: "芒果 · 14",
        meta: "摄影约拍 · 日间素材 · 芒果",
        src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-14.jpg",
        project: "芒果",
      },
      {
        id: "moto-day-芒果-芒果-15",
        cat: "moto-day",
        type: "image",
        title: "芒果 · 15",
        meta: "摄影约拍 · 日间素材 · 芒果",
        src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-15.jpg",
        project: "芒果",
      },
      {
        id: "moto-day-芒果-芒果-16",
        cat: "moto-day",
        type: "image",
        title: "芒果 · 16",
        meta: "摄影约拍 · 日间素材 · 芒果",
        src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-16.jpg",
        project: "芒果",
      },
      {
        id: "moto-day-芒果-芒果-17",
        cat: "moto-day",
        type: "image",
        title: "芒果 · 17",
        meta: "摄影约拍 · 日间素材 · 芒果",
        src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-17.jpg",
        project: "芒果",
      },
      {
        id: "moto-day-芒果-芒果-18",
        cat: "moto-day",
        type: "image",
        title: "芒果 · 18",
        meta: "摄影约拍 · 日间素材 · 芒果",
        src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-18.jpg",
        project: "芒果",
      },
      {
        id: "moto-day-芒果-芒果-19",
        cat: "moto-day",
        type: "image",
        title: "芒果 · 19",
        meta: "摄影约拍 · 日间素材 · 芒果",
        src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-19.jpg",
        project: "芒果",
      },
      {
        id: "moto-day-芒果-芒果-20",
        cat: "moto-day",
        type: "image",
        title: "芒果 · 20",
        meta: "摄影约拍 · 日间素材 · 芒果",
        src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-20.jpg",
        project: "芒果",
      },
      {
        id: "moto-day-芒果-芒果-21",
        cat: "moto-day",
        type: "image",
        title: "芒果 · 21",
        meta: "摄影约拍 · 日间素材 · 芒果",
        src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-21.jpg",
        project: "芒果",
      },
      {
        id: "moto-day-芒果-芒果-22",
        cat: "moto-day",
        type: "image",
        title: "芒果 · 22",
        meta: "摄影约拍 · 日间素材 · 芒果",
        src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-22.jpg",
        project: "芒果",
      },
      {
        id: "moto-day-芒果-芒果-23",
        cat: "moto-day",
        type: "image",
        title: "芒果 · 23",
        meta: "摄影约拍 · 日间素材 · 芒果",
        src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-23.jpg",
        project: "芒果",
      },
      {
        id: "moto-day-芒果-芒果-24",
        cat: "moto-day",
        type: "image",
        title: "芒果 · 24",
        meta: "摄影约拍 · 日间素材 · 芒果",
        src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-24.jpg",
        project: "芒果",
      },
      {
        id: "moto-day-芒果-芒果-25",
        cat: "moto-day",
        type: "image",
        title: "芒果 · 25",
        meta: "摄影约拍 · 日间素材 · 芒果",
        src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-25.jpg",
        project: "芒果",
      },
    ],
  },
];

window.AIGC_PROJECTS = [
  {
    id: "photo-zx-r绿影",
    folder: "ZX-R绿影",
    cat: "ai-design",
    title: "ZX-R 绿影",
    cover: "assets/portfolio/aigc/design/ZX-R绿影/web/moto-01.jpg",
    count: 1,
    items: [
      {
        id: "ai-design-zx-r绿影-moto-01",
        cat: "ai-design",
        type: "image",
        title: "moto 01",
        meta: "AIGC · AI 设计 · ZX-R 绿影",
        src: "assets/portfolio/aigc/design/ZX-R绿影/web/moto-01.jpg",
        project: "ZX-R绿影",
      },
    ],
  },
  {
    id: "photo-海边便利店",
    folder: "海边便利店",
    cat: "ai-design",
    title: "海边便利店",
    cover: "assets/portfolio/aigc/design/海边便利店/web/海边便利店-01.jpg",
    count: 1,
    items: [
      {
        id: "ai-design-海边便利店-海边便利店-01",
        cat: "ai-design",
        type: "image",
        title: "海边便利店 · 01",
        meta: "AIGC · AI 设计 · 海边便利店",
        src: "assets/portfolio/aigc/design/海边便利店/web/海边便利店-01.jpg",
        project: "海边便利店",
      },
    ],
  },
  {
    id: "photo-莫奈营口",
    folder: "莫奈营口",
    cat: "ai-design",
    title: "莫奈营口",
    cover: "assets/portfolio/aigc/design/莫奈营口/web/莫奈营口-01.jpg",
    count: 12,
    items: [
      {
        id: "ai-design-莫奈营口-莫奈营口-01",
        cat: "ai-design",
        type: "image",
        title: "莫奈营口 · 01",
        meta: "AIGC · AI 设计 · 莫奈营口",
        src: "assets/portfolio/aigc/design/莫奈营口/web/莫奈营口-01.jpg",
        project: "莫奈营口",
      },
      {
        id: "ai-design-莫奈营口-莫奈营口-02",
        cat: "ai-design",
        type: "image",
        title: "莫奈营口 · 02",
        meta: "AIGC · AI 设计 · 莫奈营口",
        src: "assets/portfolio/aigc/design/莫奈营口/web/莫奈营口-02.jpg",
        project: "莫奈营口",
      },
      {
        id: "ai-design-莫奈营口-莫奈营口-03",
        cat: "ai-design",
        type: "image",
        title: "莫奈营口 · 03",
        meta: "AIGC · AI 设计 · 莫奈营口",
        src: "assets/portfolio/aigc/design/莫奈营口/web/莫奈营口-03.jpg",
        project: "莫奈营口",
      },
      {
        id: "ai-design-莫奈营口-莫奈营口-04",
        cat: "ai-design",
        type: "image",
        title: "莫奈营口 · 04",
        meta: "AIGC · AI 设计 · 莫奈营口",
        src: "assets/portfolio/aigc/design/莫奈营口/web/莫奈营口-04.jpg",
        project: "莫奈营口",
      },
      {
        id: "ai-design-莫奈营口-莫奈营口-05",
        cat: "ai-design",
        type: "image",
        title: "莫奈营口 · 05",
        meta: "AIGC · AI 设计 · 莫奈营口",
        src: "assets/portfolio/aigc/design/莫奈营口/web/莫奈营口-05.jpg",
        project: "莫奈营口",
      },
      {
        id: "ai-design-莫奈营口-莫奈营口-06",
        cat: "ai-design",
        type: "image",
        title: "莫奈营口 · 06",
        meta: "AIGC · AI 设计 · 莫奈营口",
        src: "assets/portfolio/aigc/design/莫奈营口/web/莫奈营口-06.jpg",
        project: "莫奈营口",
      },
      {
        id: "ai-design-莫奈营口-莫奈营口-07",
        cat: "ai-design",
        type: "image",
        title: "莫奈营口 · 07",
        meta: "AIGC · AI 设计 · 莫奈营口",
        src: "assets/portfolio/aigc/design/莫奈营口/web/莫奈营口-07.jpg",
        project: "莫奈营口",
      },
      {
        id: "ai-design-莫奈营口-莫奈营口-08",
        cat: "ai-design",
        type: "image",
        title: "莫奈营口 · 08",
        meta: "AIGC · AI 设计 · 莫奈营口",
        src: "assets/portfolio/aigc/design/莫奈营口/web/莫奈营口-08.jpg",
        project: "莫奈营口",
      },
      {
        id: "ai-design-莫奈营口-莫奈营口-09",
        cat: "ai-design",
        type: "image",
        title: "莫奈营口 · 09",
        meta: "AIGC · AI 设计 · 莫奈营口",
        src: "assets/portfolio/aigc/design/莫奈营口/web/莫奈营口-09.jpg",
        project: "莫奈营口",
      },
      {
        id: "ai-design-莫奈营口-莫奈营口-10",
        cat: "ai-design",
        type: "image",
        title: "莫奈营口 · 10",
        meta: "AIGC · AI 设计 · 莫奈营口",
        src: "assets/portfolio/aigc/design/莫奈营口/web/莫奈营口-10.jpg",
        project: "莫奈营口",
      },
      {
        id: "ai-design-莫奈营口-莫奈营口-11",
        cat: "ai-design",
        type: "image",
        title: "莫奈营口 · 11",
        meta: "AIGC · AI 设计 · 莫奈营口",
        src: "assets/portfolio/aigc/design/莫奈营口/web/莫奈营口-11.jpg",
        project: "莫奈营口",
      },
      {
        id: "ai-design-莫奈营口-莫奈营口-12",
        cat: "ai-design",
        type: "image",
        title: "莫奈营口 · 12",
        meta: "AIGC · AI 设计 · 莫奈营口",
        src: "assets/portfolio/aigc/design/莫奈营口/web/莫奈营口-12.jpg",
        project: "莫奈营口",
      },
    ],
  },
  {
    id: "photo-彩妆广告",
    folder: "彩妆广告",
    cat: "ai-video",
    title: "彩妆广告",
    cover: "assets/portfolio/aigc/video/彩妆广告/cover.jpg",
    count: 1,
    items: [
      {
        id: "ai-video-彩妆广告-彩妆广告",
        cat: "ai-video",
        type: "video",
        title: "彩妆广告",
        meta: "AIGC · AI 视频 · 彩妆广告",
        cover: "assets/portfolio/aigc/video/彩妆广告/cover.jpg",
        src: "assets/portfolio/aigc/video/彩妆广告/彩妆广告.mp4",
        project: "彩妆广告",
      },
    ],
  },
  {
    id: "photo-未来水世界",
    folder: "未来水世界",
    cat: "ai-video",
    title: "未来水世界",
    cover: "assets/portfolio/aigc/video/未来水世界/cover.jpg",
    count: 1,
    items: [
      {
        id: "ai-video-未来水世界-未来水世界",
        cat: "ai-video",
        type: "video",
        title: "未来水世界",
        meta: "AIGC · AI 视频 · 未来水世界",
        cover: "assets/portfolio/aigc/video/未来水世界/cover.jpg",
        src: "assets/portfolio/aigc/video/未来水世界/未来水世界.mp4",
        project: "未来水世界",
      },
    ],
  },
  {
    id: "photo-疯狂的麦克斯-狂暴营口",
    folder: "疯狂的麦克斯-狂暴营口",
    cat: "ai-video",
    title: "疯狂的麦克斯 · 狂暴营口",
    cover: "assets/portfolio/aigc/video/疯狂的麦克斯-狂暴营口/cover.jpg",
    count: 1,
    items: [
      {
        id: "ai-video-疯狂的麦克斯-狂暴营口-疯狂的麦克斯-狂暴营口",
        cat: "ai-video",
        type: "video",
        title: "疯狂的麦克斯 · 狂暴营口",
        meta: "AIGC · AI 视频 · 疯狂的麦克斯 · 狂暴营口",
        cover: "assets/portfolio/aigc/video/疯狂的麦克斯-狂暴营口/cover.jpg",
        src: "assets/portfolio/aigc/video/疯狂的麦克斯-狂暴营口/疯狂的麦克斯-狂暴营口.mp4",
        project: "疯狂的麦克斯-狂暴营口",
      },
    ],
  },
  {
    id: "photo-鲅鱼公主",
    folder: "鲅鱼公主",
    cat: "ai-video",
    title: "鲅鱼公主",
    cover: "assets/portfolio/aigc/video/鲅鱼公主/cover.jpg",
    count: 1,
    items: [
      {
        id: "ai-video-鲅鱼公主-鲅鱼公主",
        cat: "ai-video",
        type: "video",
        title: "鲅鱼公主",
        meta: "AIGC · AI 视频 · 鲅鱼公主",
        cover: "assets/portfolio/aigc/video/鲅鱼公主/cover.jpg",
        src: "assets/portfolio/aigc/video/鲅鱼公主/鲅鱼公主.mp4",
        project: "鲅鱼公主",
      },
    ],
  },
];

window.PORTFOLIO_WORKS = [
  {
    id: "film-沿海公路-沿海公路",
    cat: "film",
    type: "video",
    title: "沿海公路",
    meta: "摄影约拍 · 动态跟拍 · 沿海公路",
    cover: "assets/portfolio/photo/城市追光/沿海公路/cover.jpg",
    src: "assets/portfolio/photo/城市追光/沿海公路/沿海公路.mp4",
    project: "沿海公路",
  },
  {
    id: "moto-night-夜色约拍-夜色约拍-01",
    cat: "moto-night",
    type: "image",
    title: "夜色约拍 · 01",
    meta: "摄影约拍 · 夜间素材 · 夜色约拍",
    src: "assets/portfolio/photo/夜色锋芒/夜色约拍/web/夜色约拍-01.jpg",
    project: "夜色约拍",
  },
  {
    id: "moto-night-夜色约拍-夜色约拍-02",
    cat: "moto-night",
    type: "image",
    title: "夜色约拍 · 02",
    meta: "摄影约拍 · 夜间素材 · 夜色约拍",
    src: "assets/portfolio/photo/夜色锋芒/夜色约拍/web/夜色约拍-02.jpg",
    project: "夜色约拍",
  },
  {
    id: "moto-night-夜色约拍-夜色约拍-03",
    cat: "moto-night",
    type: "image",
    title: "夜色约拍 · 03",
    meta: "摄影约拍 · 夜间素材 · 夜色约拍",
    src: "assets/portfolio/photo/夜色锋芒/夜色约拍/web/夜色约拍-03.jpg",
    project: "夜色约拍",
  },
  {
    id: "moto-night-夜色约拍-夜色约拍-04",
    cat: "moto-night",
    type: "image",
    title: "夜色约拍 · 04",
    meta: "摄影约拍 · 夜间素材 · 夜色约拍",
    src: "assets/portfolio/photo/夜色锋芒/夜色约拍/web/夜色约拍-04.jpg",
    project: "夜色约拍",
  },
  {
    id: "moto-night-夜色约拍-夜色约拍-05",
    cat: "moto-night",
    type: "image",
    title: "夜色约拍 · 05",
    meta: "摄影约拍 · 夜间素材 · 夜色约拍",
    src: "assets/portfolio/photo/夜色锋芒/夜色约拍/web/夜色约拍-05.jpg",
    project: "夜色约拍",
  },
  {
    id: "moto-night-夜色约拍-夜色约拍-06",
    cat: "moto-night",
    type: "image",
    title: "夜色约拍 · 06",
    meta: "摄影约拍 · 夜间素材 · 夜色约拍",
    src: "assets/portfolio/photo/夜色锋芒/夜色约拍/web/夜色约拍-06.jpg",
    project: "夜色约拍",
  },
  {
    id: "moto-night-夜色约拍-夜色约拍-07",
    cat: "moto-night",
    type: "image",
    title: "夜色约拍 · 07",
    meta: "摄影约拍 · 夜间素材 · 夜色约拍",
    src: "assets/portfolio/photo/夜色锋芒/夜色约拍/web/夜色约拍-07.jpg",
    project: "夜色约拍",
  },
  {
    id: "moto-day-胖胖-胖胖-01",
    cat: "moto-day",
    type: "image",
    title: "胖胖 · 01",
    meta: "摄影约拍 · 日间素材 · 胖胖",
    src: "assets/portfolio/photo/港湾日光/胖胖/web/胖胖-01.jpg",
    project: "胖胖",
  },
  {
    id: "moto-day-胖胖-胖胖-02",
    cat: "moto-day",
    type: "image",
    title: "胖胖 · 02",
    meta: "摄影约拍 · 日间素材 · 胖胖",
    src: "assets/portfolio/photo/港湾日光/胖胖/web/胖胖-02.jpg",
    project: "胖胖",
  },
  {
    id: "moto-day-胖胖-胖胖-03",
    cat: "moto-day",
    type: "image",
    title: "胖胖 · 03",
    meta: "摄影约拍 · 日间素材 · 胖胖",
    src: "assets/portfolio/photo/港湾日光/胖胖/web/胖胖-03.jpg",
    project: "胖胖",
  },
  {
    id: "moto-day-胖胖-胖胖-04",
    cat: "moto-day",
    type: "image",
    title: "胖胖 · 04",
    meta: "摄影约拍 · 日间素材 · 胖胖",
    src: "assets/portfolio/photo/港湾日光/胖胖/web/胖胖-04.jpg",
    project: "胖胖",
  },
  {
    id: "moto-day-胖胖-胖胖-05",
    cat: "moto-day",
    type: "image",
    title: "胖胖 · 05",
    meta: "摄影约拍 · 日间素材 · 胖胖",
    src: "assets/portfolio/photo/港湾日光/胖胖/web/胖胖-05.jpg",
    project: "胖胖",
  },
  {
    id: "moto-day-胖胖-胖胖-06",
    cat: "moto-day",
    type: "image",
    title: "胖胖 · 06",
    meta: "摄影约拍 · 日间素材 · 胖胖",
    src: "assets/portfolio/photo/港湾日光/胖胖/web/胖胖-06.jpg",
    project: "胖胖",
  },
  {
    id: "moto-day-胖胖-胖胖-07",
    cat: "moto-day",
    type: "image",
    title: "胖胖 · 07",
    meta: "摄影约拍 · 日间素材 · 胖胖",
    src: "assets/portfolio/photo/港湾日光/胖胖/web/胖胖-07.jpg",
    project: "胖胖",
  },
  {
    id: "moto-day-胖胖-胖胖-08",
    cat: "moto-day",
    type: "image",
    title: "胖胖 · 08",
    meta: "摄影约拍 · 日间素材 · 胖胖",
    src: "assets/portfolio/photo/港湾日光/胖胖/web/胖胖-08.jpg",
    project: "胖胖",
  },
  {
    id: "moto-day-胖胖-胖胖-09",
    cat: "moto-day",
    type: "image",
    title: "胖胖 · 09",
    meta: "摄影约拍 · 日间素材 · 胖胖",
    src: "assets/portfolio/photo/港湾日光/胖胖/web/胖胖-09.jpg",
    project: "胖胖",
  },
  {
    id: "moto-day-胖胖-胖胖-10",
    cat: "moto-day",
    type: "image",
    title: "胖胖 · 10",
    meta: "摄影约拍 · 日间素材 · 胖胖",
    src: "assets/portfolio/photo/港湾日光/胖胖/web/胖胖-10.jpg",
    project: "胖胖",
  },
  {
    id: "moto-day-芒果-芒果-01",
    cat: "moto-day",
    type: "image",
    title: "芒果 · 01",
    meta: "摄影约拍 · 日间素材 · 芒果",
    src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-01.jpg",
    project: "芒果",
  },
  {
    id: "moto-day-芒果-芒果-02",
    cat: "moto-day",
    type: "image",
    title: "芒果 · 02",
    meta: "摄影约拍 · 日间素材 · 芒果",
    src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-02.jpg",
    project: "芒果",
  },
  {
    id: "moto-day-芒果-芒果-03",
    cat: "moto-day",
    type: "image",
    title: "芒果 · 03",
    meta: "摄影约拍 · 日间素材 · 芒果",
    src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-03.jpg",
    project: "芒果",
  },
  {
    id: "moto-day-芒果-芒果-04",
    cat: "moto-day",
    type: "image",
    title: "芒果 · 04",
    meta: "摄影约拍 · 日间素材 · 芒果",
    src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-04.jpg",
    project: "芒果",
  },
  {
    id: "moto-day-芒果-芒果-05",
    cat: "moto-day",
    type: "image",
    title: "芒果 · 05",
    meta: "摄影约拍 · 日间素材 · 芒果",
    src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-05.jpg",
    project: "芒果",
  },
  {
    id: "moto-day-芒果-芒果-06",
    cat: "moto-day",
    type: "image",
    title: "芒果 · 06",
    meta: "摄影约拍 · 日间素材 · 芒果",
    src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-06.jpg",
    project: "芒果",
  },
  {
    id: "moto-day-芒果-芒果-07",
    cat: "moto-day",
    type: "image",
    title: "芒果 · 07",
    meta: "摄影约拍 · 日间素材 · 芒果",
    src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-07.jpg",
    project: "芒果",
  },
  {
    id: "moto-day-芒果-芒果-08",
    cat: "moto-day",
    type: "image",
    title: "芒果 · 08",
    meta: "摄影约拍 · 日间素材 · 芒果",
    src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-08.jpg",
    project: "芒果",
  },
  {
    id: "moto-day-芒果-芒果-09",
    cat: "moto-day",
    type: "image",
    title: "芒果 · 09",
    meta: "摄影约拍 · 日间素材 · 芒果",
    src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-09.jpg",
    project: "芒果",
  },
  {
    id: "moto-day-芒果-芒果-10",
    cat: "moto-day",
    type: "image",
    title: "芒果 · 10",
    meta: "摄影约拍 · 日间素材 · 芒果",
    src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-10.jpg",
    project: "芒果",
  },
  {
    id: "moto-day-芒果-芒果-11",
    cat: "moto-day",
    type: "image",
    title: "芒果 · 11",
    meta: "摄影约拍 · 日间素材 · 芒果",
    src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-11.jpg",
    project: "芒果",
  },
  {
    id: "moto-day-芒果-芒果-12",
    cat: "moto-day",
    type: "image",
    title: "芒果 · 12",
    meta: "摄影约拍 · 日间素材 · 芒果",
    src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-12.jpg",
    project: "芒果",
  },
  {
    id: "moto-day-芒果-芒果-13",
    cat: "moto-day",
    type: "image",
    title: "芒果 · 13",
    meta: "摄影约拍 · 日间素材 · 芒果",
    src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-13.jpg",
    project: "芒果",
  },
  {
    id: "moto-day-芒果-芒果-14",
    cat: "moto-day",
    type: "image",
    title: "芒果 · 14",
    meta: "摄影约拍 · 日间素材 · 芒果",
    src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-14.jpg",
    project: "芒果",
  },
  {
    id: "moto-day-芒果-芒果-15",
    cat: "moto-day",
    type: "image",
    title: "芒果 · 15",
    meta: "摄影约拍 · 日间素材 · 芒果",
    src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-15.jpg",
    project: "芒果",
  },
  {
    id: "moto-day-芒果-芒果-16",
    cat: "moto-day",
    type: "image",
    title: "芒果 · 16",
    meta: "摄影约拍 · 日间素材 · 芒果",
    src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-16.jpg",
    project: "芒果",
  },
  {
    id: "moto-day-芒果-芒果-17",
    cat: "moto-day",
    type: "image",
    title: "芒果 · 17",
    meta: "摄影约拍 · 日间素材 · 芒果",
    src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-17.jpg",
    project: "芒果",
  },
  {
    id: "moto-day-芒果-芒果-18",
    cat: "moto-day",
    type: "image",
    title: "芒果 · 18",
    meta: "摄影约拍 · 日间素材 · 芒果",
    src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-18.jpg",
    project: "芒果",
  },
  {
    id: "moto-day-芒果-芒果-19",
    cat: "moto-day",
    type: "image",
    title: "芒果 · 19",
    meta: "摄影约拍 · 日间素材 · 芒果",
    src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-19.jpg",
    project: "芒果",
  },
  {
    id: "moto-day-芒果-芒果-20",
    cat: "moto-day",
    type: "image",
    title: "芒果 · 20",
    meta: "摄影约拍 · 日间素材 · 芒果",
    src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-20.jpg",
    project: "芒果",
  },
  {
    id: "moto-day-芒果-芒果-21",
    cat: "moto-day",
    type: "image",
    title: "芒果 · 21",
    meta: "摄影约拍 · 日间素材 · 芒果",
    src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-21.jpg",
    project: "芒果",
  },
  {
    id: "moto-day-芒果-芒果-22",
    cat: "moto-day",
    type: "image",
    title: "芒果 · 22",
    meta: "摄影约拍 · 日间素材 · 芒果",
    src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-22.jpg",
    project: "芒果",
  },
  {
    id: "moto-day-芒果-芒果-23",
    cat: "moto-day",
    type: "image",
    title: "芒果 · 23",
    meta: "摄影约拍 · 日间素材 · 芒果",
    src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-23.jpg",
    project: "芒果",
  },
  {
    id: "moto-day-芒果-芒果-24",
    cat: "moto-day",
    type: "image",
    title: "芒果 · 24",
    meta: "摄影约拍 · 日间素材 · 芒果",
    src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-24.jpg",
    project: "芒果",
  },
  {
    id: "moto-day-芒果-芒果-25",
    cat: "moto-day",
    type: "image",
    title: "芒果 · 25",
    meta: "摄影约拍 · 日间素材 · 芒果",
    src: "assets/portfolio/photo/港湾日光/芒果/web/芒果-25.jpg",
    project: "芒果",
  },
  {
    id: "ai-design-zx-r绿影-moto-01",
    cat: "ai-design",
    type: "image",
    title: "moto 01",
    meta: "AIGC · AI 设计 · ZX-R 绿影",
    src: "assets/portfolio/aigc/design/ZX-R绿影/web/moto-01.jpg",
    project: "ZX-R绿影",
  },
  {
    id: "ai-design-海边便利店-海边便利店-01",
    cat: "ai-design",
    type: "image",
    title: "海边便利店 · 01",
    meta: "AIGC · AI 设计 · 海边便利店",
    src: "assets/portfolio/aigc/design/海边便利店/web/海边便利店-01.jpg",
    project: "海边便利店",
  },
  {
    id: "ai-design-莫奈营口-莫奈营口-01",
    cat: "ai-design",
    type: "image",
    title: "莫奈营口 · 01",
    meta: "AIGC · AI 设计 · 莫奈营口",
    src: "assets/portfolio/aigc/design/莫奈营口/web/莫奈营口-01.jpg",
    project: "莫奈营口",
  },
  {
    id: "ai-design-莫奈营口-莫奈营口-02",
    cat: "ai-design",
    type: "image",
    title: "莫奈营口 · 02",
    meta: "AIGC · AI 设计 · 莫奈营口",
    src: "assets/portfolio/aigc/design/莫奈营口/web/莫奈营口-02.jpg",
    project: "莫奈营口",
  },
  {
    id: "ai-design-莫奈营口-莫奈营口-03",
    cat: "ai-design",
    type: "image",
    title: "莫奈营口 · 03",
    meta: "AIGC · AI 设计 · 莫奈营口",
    src: "assets/portfolio/aigc/design/莫奈营口/web/莫奈营口-03.jpg",
    project: "莫奈营口",
  },
  {
    id: "ai-design-莫奈营口-莫奈营口-04",
    cat: "ai-design",
    type: "image",
    title: "莫奈营口 · 04",
    meta: "AIGC · AI 设计 · 莫奈营口",
    src: "assets/portfolio/aigc/design/莫奈营口/web/莫奈营口-04.jpg",
    project: "莫奈营口",
  },
  {
    id: "ai-design-莫奈营口-莫奈营口-05",
    cat: "ai-design",
    type: "image",
    title: "莫奈营口 · 05",
    meta: "AIGC · AI 设计 · 莫奈营口",
    src: "assets/portfolio/aigc/design/莫奈营口/web/莫奈营口-05.jpg",
    project: "莫奈营口",
  },
  {
    id: "ai-design-莫奈营口-莫奈营口-06",
    cat: "ai-design",
    type: "image",
    title: "莫奈营口 · 06",
    meta: "AIGC · AI 设计 · 莫奈营口",
    src: "assets/portfolio/aigc/design/莫奈营口/web/莫奈营口-06.jpg",
    project: "莫奈营口",
  },
  {
    id: "ai-design-莫奈营口-莫奈营口-07",
    cat: "ai-design",
    type: "image",
    title: "莫奈营口 · 07",
    meta: "AIGC · AI 设计 · 莫奈营口",
    src: "assets/portfolio/aigc/design/莫奈营口/web/莫奈营口-07.jpg",
    project: "莫奈营口",
  },
  {
    id: "ai-design-莫奈营口-莫奈营口-08",
    cat: "ai-design",
    type: "image",
    title: "莫奈营口 · 08",
    meta: "AIGC · AI 设计 · 莫奈营口",
    src: "assets/portfolio/aigc/design/莫奈营口/web/莫奈营口-08.jpg",
    project: "莫奈营口",
  },
  {
    id: "ai-design-莫奈营口-莫奈营口-09",
    cat: "ai-design",
    type: "image",
    title: "莫奈营口 · 09",
    meta: "AIGC · AI 设计 · 莫奈营口",
    src: "assets/portfolio/aigc/design/莫奈营口/web/莫奈营口-09.jpg",
    project: "莫奈营口",
  },
  {
    id: "ai-design-莫奈营口-莫奈营口-10",
    cat: "ai-design",
    type: "image",
    title: "莫奈营口 · 10",
    meta: "AIGC · AI 设计 · 莫奈营口",
    src: "assets/portfolio/aigc/design/莫奈营口/web/莫奈营口-10.jpg",
    project: "莫奈营口",
  },
  {
    id: "ai-design-莫奈营口-莫奈营口-11",
    cat: "ai-design",
    type: "image",
    title: "莫奈营口 · 11",
    meta: "AIGC · AI 设计 · 莫奈营口",
    src: "assets/portfolio/aigc/design/莫奈营口/web/莫奈营口-11.jpg",
    project: "莫奈营口",
  },
  {
    id: "ai-design-莫奈营口-莫奈营口-12",
    cat: "ai-design",
    type: "image",
    title: "莫奈营口 · 12",
    meta: "AIGC · AI 设计 · 莫奈营口",
    src: "assets/portfolio/aigc/design/莫奈营口/web/莫奈营口-12.jpg",
    project: "莫奈营口",
  },
  {
    id: "ai-video-彩妆广告-彩妆广告",
    cat: "ai-video",
    type: "video",
    title: "彩妆广告",
    meta: "AIGC · AI 视频 · 彩妆广告",
    cover: "assets/portfolio/aigc/video/彩妆广告/cover.jpg",
    src: "assets/portfolio/aigc/video/彩妆广告/彩妆广告.mp4",
    project: "彩妆广告",
  },
  {
    id: "ai-video-未来水世界-未来水世界",
    cat: "ai-video",
    type: "video",
    title: "未来水世界",
    meta: "AIGC · AI 视频 · 未来水世界",
    cover: "assets/portfolio/aigc/video/未来水世界/cover.jpg",
    src: "assets/portfolio/aigc/video/未来水世界/未来水世界.mp4",
    project: "未来水世界",
  },
  {
    id: "ai-video-疯狂的麦克斯-狂暴营口-疯狂的麦克斯-狂暴营口",
    cat: "ai-video",
    type: "video",
    title: "疯狂的麦克斯 · 狂暴营口",
    meta: "AIGC · AI 视频 · 疯狂的麦克斯 · 狂暴营口",
    cover: "assets/portfolio/aigc/video/疯狂的麦克斯-狂暴营口/cover.jpg",
    src: "assets/portfolio/aigc/video/疯狂的麦克斯-狂暴营口/疯狂的麦克斯-狂暴营口.mp4",
    project: "疯狂的麦克斯-狂暴营口",
  },
  {
    id: "ai-video-鲅鱼公主-鲅鱼公主",
    cat: "ai-video",
    type: "video",
    title: "鲅鱼公主",
    meta: "AIGC · AI 视频 · 鲅鱼公主",
    cover: "assets/portfolio/aigc/video/鲅鱼公主/cover.jpg",
    src: "assets/portfolio/aigc/video/鲅鱼公主/鲅鱼公主.mp4",
    project: "鲅鱼公主",
  },
];

window.PORTFOLIO_CATEGORIES = {
  all: { label: "全部", parent: null },
  photo: { label: "摄影约拍", parent: null, children: ["film", "moto-night", "moto-day"] },
  film: { label: "城市追光 · 动态跟拍", parent: "photo", empty: "请往 photo/城市追光/ 上传跟拍视频。" },
  "moto-night": { label: "夜色锋芒 · 夜间素材", parent: "photo", empty: "请往 photo/夜色锋芒/ 上传夜景作品。" },
  "moto-day": { label: "港湾日光 · 日间素材", parent: "photo", empty: "请往 photo/港湾日光/ 上传日间作品。" },
  aigc: { label: "AIGC 作品", parent: null, children: ["ai-video", "ai-design"] },
  "ai-video": { label: "AI 视频", parent: "aigc", empty: "AI 视频项目陆续更新中。" },
  "ai-design": { label: "AI 设计", parent: "aigc", empty: "AI 设计项目陆续更新中。" },
};

